### ISSUE TITLE
problem with mailx on Debian 9

### ISSUE THREAD

**Issue by jayalpes** [ltb-project/ldap-scripts#17]
Hi,
the 'From;...' in the body of the message (MY_MAIL_BODY) doesn't work as expected with mailx. The from cames in the message and isn't used by mailx.
If we use sendmail it's good for the from but sendmail doesn't use the '-s' option for the subject so we have to change your good script.
Can you find a solution ?

**Comment by coudot** [comment]
You mean CentOS 8?

**Comment by jayalpes** [comment]
I was tired, it's Debian 9 and bsd-mailx (version 8.1.2-0.20160123cvs-4)
To test I change your "Sending mail ..." to add '-r ' and I put the 'from' like this : 
```
# Sending mail...
[ -z "${MY_MAIL_FROM}" ] || MY_MAIL_BIN="${MY_MAIL_BIN} -r " #MY_MAIL_FROM="-r '${MY_MAIL_FROM}'"
echo "${logmsg}" | ${MY_MAIL_BIN} "${MY_MAIL_FROM}" -s "${MY_MAIL_SUBJECT}" ${mail} >&2

```

**Comment by jayalpes** [comment]
I have made a fork with this change : https://github.com/jayalpes/ldap-scripts

**Comment by coudot** [comment]
Thanks, could you do a PR?

**Comment by coudot** [comment]
@jayalpes could you confirm that the accepted PR are enough to fix this issue?

**Comment by jayalpes** [comment]
yes it's (used like this since 10 days)

**Comment by coudot** [comment]
Thanks for the feedback
