### ISSUE TITLE
problem with the global search

### ISSUE THREAD

**Issue by jayalpes** [ltb-project/ldap-scripts#18]
Hi,
I had to put a grep to filter some commented lines comming in the search response :
```
## Performs global search
${MY_LDAP_SEARCHBIN} ${ldap_param} -s ${MY_LDAP_SEARCHSCOPE} \
  -b "${MY_LDAP_SEARCHBASE}" "${MY_LDAP_SEARCHFILTER}" \
  "dn" **| grep -iE '^dn:'** > ${result_file}
```

Without this my global result give me : 
```
dn: cnxxxx

dn: cnyyyy

# ....

dn: cnxxxx

dn: cnyyyy
```

**Comment by coudot** [comment]
I don't understand, as result_file must contain dn

Could you try the latest script version from this git repo?

**Comment by jayalpes** [comment]
I have an openLdap which restrict the number of entries that a client can retrieve in a single operation to 500.
So I use ' -E pr=500/noprompt' with ldapsearch and so it return 500 lines with dn: cn=.... and blank lines. and then '# pagedresults: cookie= ' and next 500 lines ...
Like this :
```
dn: cnxxxx

dn: cnyyyy

# pagedresults: cookie= 

dn: cnxxxx

dn: cnyyyy
```

So with 'grep -E '^dn:' you keep enly the good lines.

**Comment by jayalpes** [comment]
I have made a fork with this change : https://github.com/jayalpes/ldap-scripts

**Comment by coudot** [comment]
Thanks, could you do a PR?

**Comment by coudot** [comment]
@jayalpes could you confirm that the accepted PR are enough to fix this issue?

**Comment by jayalpes** [comment]
yes this fix this issue

**Comment by coudot** [comment]
Thanks for the feedback
