### ISSUE TITLE
Issue in ldap-stats.pl

### ISSUE THREAD

**Issue by Oliv-78** [ltb-project/ldap-scripts#34]
Hello,

This is an issue in ldap-stats.pl on line 636

my $binddn = lc $$; must be **my $binddn = lc $3;**

We don't have to log the process number 😁

![image](https://github.com/ltb-project/ldap-scripts/assets/71079960/a9a9eddb-39db-4817-8f45-abdea8c854ef)

**Comment by davidcoutadeur** [comment]
Thanks for the report!

It's a regression brought by a new feature I have implemented: "Process greater qtimes and etimes". (see #31), appearing in commit f496723d

I have just fixed it in 7390d50
