### ISSUE TITLE
file2ldif : bad substitution in destination LDIF when using several source attributes

### ISSUE THREAD

**Issue by nqb** [ltb-project/ldap-scripts#4]
Hello,

I notice a bad substitution in destination LDIF if I use several source attributes to compute a destination attribute.

### Steps to reproduce : 
1. Create an example LDIF (`example.ldif`) : 
```
dn: cn=clide,ou=users,dc=acme,dc=com
objectClass: top
objectClass: person
cn: clide
givenname: foo
sn: barrow
employeeType: gangster
```
2. Define a task that use several source attributes to compute a destination attribute (here `displayname`) : 
```
# Mapping configuration
my $map = {
    l_person => {
        dn           => '{dn}',
        cn           => '{sn}',
        displayName  => '{givenName} {sn} {employeetype}',
    },
```
3. Launch your task : `perl file2ldif.pl l_person example.ldif`

### Actual results in `l_person.ldif` : 
```
dn: cn=clide,ou=users,dc=acme,dc=com
changetype: add
cn: barrow
displayName: foo foo foo                                 <<<<
```

### Expected results in `l_person.ldif` : 
```
dn: cn=clide,ou=users,dc=acme,dc=com
changetype: add
cn: barrow
displayName: foo barrow gangster                         <<<<
```

After several tests, I think there is an issue in following regex : https://github.com/ltb-project/ldap-scripts/blob/6e50aa5da202193693e0c8000315e58d76f7a308/file2ldif.pl#L274

That regex can't return several source attributes.

**Comment by coudot** [comment]
Indeed, it should work, as we have this in examples:
```perl
    l_person => {
        dn => 'uid={(lc)uid},ou=users,dc=example,dc=com',
        objectClass =>
          [ 'top', 'person', 'organizationalPerson', 'inetOrgPerson' ],
        cn        => '{cn}',
        sn        => '{(uc)sn}',
        givenName => '{(ucfirstlc)givenname}',
        mail      => '{(fmail)givenname}.{(fmail)sn}@example.com',
    },
```

**Comment by nqb** [comment]
Completely agree with you @coudot. It's a regression.

If you try to reproduce at https://github.com/ltb-project/ldap-scripts/commit/0bb52705b5c1775a3b3a7ffee6e76156e3a052db, you can't. Bug is not present.

Bug was introduced by https://github.com/ltb-project/ldap-scripts/commit/26fbb65b534dad3383436f550c495d63f2af62a6. At this commit, you can reproduce.

**Comment by coudot** [comment]
Not so easy to fix, we need to choose if we replace multiple keys in a map or multiple values for a key. I made a change in latest commit so it should in most of the cases.

**Comment by nqb** [comment]
It works for me.

**Comment by coudot** [comment]
Great!
